blog/urls.py
from functools import partial
from django.views import defaults

from django.urls import path
from . import views
from .views import (PostListView, PostCreateView, PostUpdateView, 
                    PostDeleteView, UserPostListView, search, filterr, pollindex, 
                    polldetail, pollresults, pollvote, user_detail, user_list, 
                    post_detail, gone, PostLikeView, PostUnlikeView,
                    PostSaveView, PostUnSaveView)

urlpatterns = [
    path('', PostListView.as_view(), name='blog-home'),
    # display post from certain user
    path('user/<str:username>', UserPostListView.as_view(), name='user-posts'),
    # view the post
    path('post/<int:pk>', views.post_detail, name='post-detail'),
    # create a new post
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    # update a post
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    # delete a post 
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),

    # like, dislike posts
    path('<int:id>/like/', PostLikeView.as_view(), name='post-likes'),
    path('<int:id>/unlike/', PostUnlikeView.as_view(), name='post-unlikes'),

    # save, unsave posts
    path('<int:id>/save/', PostSaveView.as_view(), name='post-save'),
    path('<int:id>/unsave/', PostUnSaveView.as_view(), name='post-unsave'),

    # search 
    path('results/', views.search, name='search'),
    # path('results/users/', views.search_user, name='search-user'),
    
    # profile user detail
    path('profile/<username>', views.user_detail, name='user-detail'),

    # following users
    path('users/follow/', views.user_follow, name='user_follow'),

    # filters
    path('filter/<str:tags>', PostListView.as_view(), name='filter'),
    path('filter/selenium/', views.filterr, name='filter-sele'),
    path('filter/django/', views.filterr, name='filter-django'),
    path('filter/react/', views.filterr, name='filter-react'),
    path('filter/python/', views.filterr, name='filter-python'),
    path('filter/maths/', views.filterr, name='filter-maths'),
    path('filter/java/', views.filterr, name='filter-java'),
    path('filter/js/', views.filterr, name='filter-javascript'),
    path('filter/algorithms/', views.filterr, name='filter-algo'),
    path('filter/csharp/', views.filterr, name='filter-csharp'),
    path('filter/discussion/', views.filterr, name='filter-discussion'),
    path('filter/cybersec/', views.filterr, name='filter-cybersec'),

    # polls
    path('polls/', views.pollindex, name='pollindex'),
    path('polls/<int:question_id>/', views.polldetail, name='polldetail'),
    path('polls/<int:question_id>/results/', views.pollresults, name='pollresults'),
    path('polls/<int:question_id>/vote/', views.pollvote, name='pollvote'),

    # users list
    path('users/', views.user_list, name="users-list"),

    path('news/', views.news, name='news'),
    path('about/', views.about, name='blog-about'),
    path('contact/', views.contact, name='blog-contact'),

    path('400/', partial(defaults.bad_request, exception=None)),
    path('403/', partial(defaults.permission_denied, exception=None)),
    path('404/', partial(defaults.page_not_found, exception=None)),
    path('410/', gone),
    path('500/', defaults.server_error),
]

chat/urls.py
from django.urls import path, re_path

from .views import ThreadView, InboxView

app_name = 'chat'
urlpatterns = [
    path("", InboxView.as_view(), name="chat-inbox"),
    re_path(r"^(?P<username>[\w.@+-]+)", ThreadView.as_view(), name='chat-detail'),
]

django_project/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views
from chat import views as chat_views
from blog import views as blog_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),

    ### settings ###
    path('settings/', user_views.user_settings, name='user_settings'),
    path('settings/github/', user_views.settings_github, name='settings_github'),
    path('settings/rss-config/', user_views.settings_rss, name='settings_rss'),
    path('settings/rss-config/<int:pk>/delete/', blog_views.RssDeleteView.as_view(), name='delete-rss'),


    # password reset urls...
    path('password-reset/', 
        auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), 
        name='password_reset'),
    path('password-reset/done/', 
        auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), 
        name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', 
        auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), 
        name='password_reset_confirm'),

    path('tinymce/', include('tinymce.urls')),
    path('trix/', include('trix.urls')),
    path('accounts/', include('allauth.urls')),

    path('chat/', include('chat.urls')),
    path('', include('blog.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

chat/models.py
from django.db import models

from django.conf import settings
from django.db import models
from django.db.models import Q


class ThreadManager(models.Manager):
    def by_user(self, user):
        qlookup = Q(first=user) | Q(second=user)
        qlookup2 = Q(first=user) & Q(second=user)
        qs = self.get_queryset().filter(qlookup).exclude(qlookup2).distinct()
        return qs

    def get_or_new(self, user, other_username): # get_or_create
        username = user.username
        if username == other_username:
            return None
        qlookup1 = Q(first__username=username) & Q(second__username=other_username)
        qlookup2 = Q(first__username=other_username) & Q(second__username=username)
        qs = self.get_queryset().filter(qlookup1 | qlookup2).distinct()
        if qs.count() == 1:
            return qs.first(), False
        elif qs.count() > 1:
            return qs.order_by('timestamp').first(), False
        else:
            Klass = user.__class__
            user2 = Klass.objects.get(username=other_username)
            if user != user2:
                obj = self.model(
                        first=user, 
                        second=user2
                    )
                obj.save()
                return obj, True
            return None, False


class Thread(models.Model):
    first        = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='chat_thread_first')
    second       = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='chat_thread_second')
    updated      = models.DateTimeField(auto_now=True)
    timestamp    = models.DateTimeField(auto_now_add=True)
    
    objects      = ThreadManager()

    @property
    def room_group_name(self):
        return f'chat_{self.id}'

    def broadcast(self, msg=None):
        if msg is not None:
            broadcast_msg_to_chat(msg, group_name=self.room_group_name, user='admin')
            return True
        return False


class ChatMessage(models.Model):
    thread      = models.ForeignKey(Thread, null=True, blank=True, on_delete=models.SET_NULL)
    user        = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='sender', on_delete=models.CASCADE)
    message     = models.TextField()
    timestamp   = models.DateTimeField(auto_now_add=True)

chat/forms.py
from django import forms


class ComposeForm(forms.Form):
    message = forms.CharField(
            widget=forms.TextInput(
                attrs={"class": "form-control"}
                )
            )

chat/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404, HttpResponseForbidden
from django.shortcuts import render
from django.urls import reverse
from django.views.generic.edit import FormMixin

from django.views.generic import DetailView, ListView
from django.contrib.auth.models import User

from .forms import ComposeForm
from .models import Thread, ChatMessage

from blog.views_methods import get_follow_names


class InboxView(LoginRequiredMixin, ListView):
    template_name = 'chat/inbox.html'
    model = Thread

    def get_context_data(self, **kwargs):
        context = super(InboxView, self).get_context_data(**kwargs)

        thread = Thread.objects.by_user(self.request.user)
        names = get_follow_names(self.request).exclude(id=self.request.user.id)

        context.update({
            'thread':thread,
            #'users': User.objects.exclude(id=self.request.user.id),
            'users':names
        })
        return context


class ThreadView(LoginRequiredMixin, FormMixin, DetailView):
    template_name = 'chat/thread.html'
    form_class = ComposeForm
    success_url = './'

    def get_queryset(self):
        return Thread.objects.by_user(self.request.user)

    def get_object(self):
        other_username  = self.kwargs.get("username")
        obj, created    = Thread.objects.get_or_new(self.request.user, other_username)
        if obj == None:
            raise Http404
        return obj

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.get_form()

        names = get_follow_names(self.request).exclude(id=self.request.user.id)

        context.update({
            # 'users': User.objects.exclude(id=self.request.user.id),
            'users':names
        })
        return context

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        thread = self.get_object()
        user = self.request.user
        message = form.cleaned_data.get("message")
        ChatMessage.objects.create(user=user, thread=thread, message=message)
        return super().form_valid(form)

chat/templates/chat/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

{% block head %}
  {% include 'blog/head.html' %}
{% endblock head %}

</head>

{% url 'chat:chat-detail' as cdetail %}
{% if request.path == cdetail %}
<body style="background: linear-gradient(-45deg, #ee7752, #9e6e81, #65a9c1, #8891d0);
    background-size: 400% 400%;">
{% else %}
<body>


{% endif %}

    {% block header %}
      {% include 'chat/header.html' %}
    {% endblock header %}

    <main role="main" class="container" style="padding-top:46px">
      

    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
          {{ message }}
        </div>
      {% endfor %}
    {% endif %}
    
    {% block content %}
    
    {% endblock %}

    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->

    <script src='{% static "blog/js/confirmlogout.js" %}'></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script>document.addEventListener("touchstart", function(){}, true);</script>
    <script>

            // check for saved 'darkMode' in localStorage
      let darkMode = localStorage.getItem('darkMode'); 

      const darkModeToggle = document.querySelector('#dark-mode-toggle');

      const enableDarkMode = () => {
        // 1. Add the class to the body
        document.body.classList.add('darkmode');
        // 2. Update darkMode in localStorage
        localStorage.setItem('darkMode', 'enabled');
      }

      const disableDarkMode = () => {
        // 1. Remove the class from the body
        document.body.classList.remove('darkmode');
        // 2. Update darkMode in localStorage 
        localStorage.setItem('darkMode', null);
      }
      
      // If the user already visited and enabled darkMode
      // start things off with it on
      if (darkMode === 'enabled') {
        enableDarkMode();
      }

      // When someone clicks the button
      darkModeToggle.addEventListener('click', () => {
        // get their darkMode setting
        darkMode = localStorage.getItem('darkMode'); 
        
        // if it not current enabled, enable it
        if (darkMode !== 'enabled') {
          enableDarkMode();
        // if it has been enabled, turn it off  
        } else {  
          disableDarkMode(); 
        }
      });

    </script>

    

</body>
</html>

chat/templates/chat/header.html
{% block header %}
{% load static %}

    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'blog-home' %}" style="box-shadow: 0px 14px 20px #343a40;">DOTpost</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">

            </div>
            <!-- Navbar Right Side -->

              <!-- Search feature -->
              <div class="navbar-nav">

              <!-- Login, Sign up, profile buttons -->

              {% if user.is_authenticated %}

                <a class="nav-item nav-link" href="{% url 'post-create' %}" style="box-shadow: 0.5px 0.5px 0.5px 0.5px black;">
                  <img style="width:15px;height:30px;filter:invert(1)" src="{% static 'assets/logos/publish.svg' %}" alt="publish-logo"> Publish
                </a>

                <a class="nav-item nav-link" href="{% url 'chat:chat-inbox'%}" style="box-shadow: 0.5px 0.5px 0.5px 0.5px black;">
                  <img style="width:15px;height:30px;filter:invert(1)" src="{% static 'assets/logos/chat.svg' %}" alt="logout-logo">
                </a>


                <div class="dropdown" style="padding:0px;">
                <a class="nav-item nav-link" href="{% url 'profile' %}" style="box-shadow: 0.5px 0.5px 0.5px 0.5px black;">
                  <img style="width:15px;height:30px;filter:invert(1)" src="{% static 'assets/logos/user.svg' %}" alt="profile-logo"> 
                    <button style="background-color:#343a40; border-color: #343a40; color:#d5dbde;"></button>
                </a>
                      <div class="dropdown-content">
                        <a href="{% url 'profile' %}">Profile</a>
                        <a href="{% url 'user_settings' %}">Settings</a>
                      </div>
                </div>

                <a class="nav-item nav-link" onclick="showConfirm()" href="#" style="box-shadow: 0.5px 0.5px 0.5px 0.5px black;">
                  <img style="width:15px;height:30px;filter:invert(1)" src="{% static 'assets/logos/power.svg' %}" alt="logout-logo">
                </a>

              {% else %}

                <a class="nav-item nav-link" href="{% url 'login' %}" style="box-shadow: 0.5px 0.5px 0.5px 0.5px black;">
                  <img style="width:15px;height:30px;filter:invert(1)" src="{% static 'assets/logos/login.svg' %}" alt="login-logo"> Login
                </a>
                <a class="nav-item nav-link" href="{% url 'register' %}" style="box-shadow: 0.5px 0.5px 0.5px 0.5px black;">
                  <img class="svgwhite" style="width:15px;height:30px;filter:invert(1)" src="{% static 'assets/logos/register.svg' %}" alt="register-logo"> Register
                </a>

              {% endif %}

              </div>

              <button id="dark-mode-toggle" class="dark-mode-toggle">
                <svg style="width:15px;height:30px" width="100%" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 496 496"><path fill="currentColor" d="M8,256C8,393,119,504,256,504S504,393,504,256,393,8,256,8,8,119,8,256ZM256,440V72a184,184,0,0,1,0,368Z" transform="translate(-8 -8)"/></svg>
              </button>

            </div>
          </div>
        </div> 
      </nav>
    </header>

{% endblock header %}

chat/templates/chat/inbox.html
{% extends "chat/base.html" %}
{% load crispy_forms_tags %}

{% block content %}


<div class="row">
  <div class="col-3">
    <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
    <h3>Contact list</h3>
    {% if users %}
      {% for user in users %}
        <a class="nav-link" href="{% url 'chat:chat-detail' user.username %}" >{{ user }}</a>
      {% endfor %}
    {% else %}
    <p>It looks like you have no contact, make sure to follow someone!</p>
    {% endif %}
    </div>
  </div>
  <div class="col-9">
  
  </div>
</div>

{% endblock %}

chat/templates/chat/thread.html
{% extends "chat/base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div class="chat-frame">
  <div class="row" style="padding: 20px;">
    <div class="col-3 chat-contact">
        <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
        <h3 style="padding-top: 12px;"><span class="material-icons">contacts</span> Contacts</h3>
        {% for user in users %}
            <a class="nav-link" href="{% url 'chat:chat-detail' user.username %}" >{{ user }}</a>
        {% endfor %}

        </div>
    </div>
    <div class="col-9 chat-messages">
        <h3>Your conversation with {% if user != object.first %}@{{ object.first }}{% else %}@{{ object.second }}{% endif %}</h3><br/>
        <ul id='chat-items'>
        {% for chat in object.chatmessage_set.all|slice:"2::" %}

            <li>{{ chat.user }}: {{ chat.message }}</li>

        {% endfor %}
        </ul>

        <form id='form' method='POST'> 
            <input type='hidden' id='myUsername' value='{{ user.username }}'/>
            {% csrf_token %}
            {{form|crispy}}
            <input type='submit' class='btn btn-primary'/>
        </form>
    </div>
  </div>
</div>










<script src="https://cdnjs.cloudflare.com/ajax/libs/reconnecting-websocket/1.0.0/reconnecting-websocket.js"></script>
<script>
// websocket scripts

var loc = window.location;
var formData = $("#form")
var msgInput = $("#id_message")
var chatHolder = $("#chat-items")
var me = $("#myUsername").val()

var wsStart = 'ws://';
if (loc.protocol == 'https:'){
    wsStart = 'wss://'
};

var endpoint = wsStart + loc.host + loc.pathname + '/';
var socket = new ReconnectingWebSocket(endpoint);

socket.onmessage = function(e){
    console.log("message",e)
    var chatDataMsg = JSON.parse(e.data)
    chatHolder.append("<li>" + chatDataMsg.username + ": " + chatDataMsg.message + "</li>")
};

socket.onopen = function(e){
    console.log("open",e)
    formData.submit(function(event){
        event.preventDefault()
        var msgText = msgInput.val()
        // chatHolder.append("<li>" + msgText + " via " + me +  "</li>")
        
        var finalData = {
            'message':msgText
        }
        socket.send(JSON.stringify(finalData))
        // msgInput.val('')
        formData[0].reset()
    })
};

socket.onerror = function(e){
    console.log("error",e)
};

socket.onclose = function(e){
    console.log("close",e)
};

</script>

{% endblock %}